-- MySQL Script generated by MySQL Workbench
-- Thu Feb 21 15:59:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`major` ;

CREATE TABLE IF NOT EXISTS `mydb`.`major` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marjor_name` VARCHAR(45) NOT NULL,
  `class` INT NOT NULL,
  `grade` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stu_id` VARCHAR(15) NOT NULL,
  `stu_name` VARCHAR(10) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `avatar_path` VARCHAR(50) NOT NULL,
  `personalized_signatures` VARCHAR(50) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `sex` ENUM("男", "女") NOT NULL,
  `major_id` INT NOT NULL,
  PRIMARY KEY (`id`, `major_id`),
  INDEX `fk_student_major1_idx` (`major_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_major1`
    FOREIGN KEY (`major_id`)
    REFERENCES `mydb`.`major` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teacher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teacher_name` VARCHAR(10) NOT NULL,
  `avatar_path` VARCHAR(255) NOT NULL COMMENT '头像路径',
  `office` VARCHAR(50) NULL,
  `phone_number` VARCHAR(50) NULL,
  `e-mail` VARCHAR(50) NULL,
  `likes_number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(20) NOT NULL,
  `classroom` VARCHAR(45) NOT NULL,
  `course_credit` FLOAT NULL COMMENT '学分',
  `course_hour` INT NULL COMMENT '课时',
  `course_quota` INT NULL COMMENT '课程名额',
  `day_of_week` TINYINT UNSIGNED NOT NULL,
  `week_of_semester` TINYINT UNSIGNED NOT NULL COMMENT '课程周次',
  `lesson_of_day` TINYINT UNSIGNED NOT NULL COMMENT '课程节次',
  `course_year` VARCHAR(10) NOT NULL COMMENT '学年',
  `course_type` ENUM("必修", "人文", "科学", "工程", "体育") NULL,
  `course_time` VARCHAR(45) NULL COMMENT '上课时间 10:00-12:00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`examination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`examination` ;

CREATE TABLE IF NOT EXISTS `mydb`.`examination` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `site` VARCHAR(45) NOT NULL,
  `invigilator` VARCHAR(45) NOT NULL COMMENT '监考老师',
  `day_of_week` TINYINT NOT NULL,
  `week_of_semester` TINYINT NOT NULL,
  `exam_time` VARCHAR(45) NOT NULL COMMENT '考试时间 10:00-12:00',
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`, `course_id`),
  INDEX `fk_examination_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_examination_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stu_exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stu_exam` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stu_exam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seat_number` INT NULL,
  `examination_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`, `examination_id`, `student_id`),
  INDEX `fk_stu_exam_examination1_idx` (`examination_id` ASC) VISIBLE,
  INDEX `fk_stu_exam_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_stu_exam_examination1`
    FOREIGN KEY (`examination_id`)
    REFERENCES `mydb`.`examination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_exam_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`score` ;

CREATE TABLE IF NOT EXISTS `mydb`.`score` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `score` INT UNSIGNED NOT NULL,
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`, `student_id`, `course_id`),
  INDEX `fk_score_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_score_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_score_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bullet_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bullet_comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bullet_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `week_of_semester` TINYINT NOT NULL,
  `content` VARCHAR(100) NOT NULL,
  `student_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `academic_year` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `student_id`, `major_id`),
  INDEX `fk_bullet_comments_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_bullet_comments_major1_idx` (`major_id` ASC) VISIBLE,
  CONSTRAINT `fk_bullet_comments_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bullet_comments_major1`
    FOREIGN KEY (`major_id`)
    REFERENCES `mydb`.`major` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`elective`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`elective` ;

CREATE TABLE IF NOT EXISTS `mydb`.`elective` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `likes_number` INT UNSIGNED NOT NULL,
  `collectons_number` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`elective_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`elective_comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`elective_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment_content` VARCHAR(255) NOT NULL,
  `comment_time` TIMESTAMP NOT NULL,
  `elective_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`, `elective_id`, `student_id`),
  INDEX `fk_elective_comments_elective_items1_idx` (`elective_id` ASC) VISIBLE,
  INDEX `fk_elective_comments_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_elective_comments_elective_items1`
    FOREIGN KEY (`elective_id`)
    REFERENCES `mydb`.`elective` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_elective_comments_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`match` ;

CREATE TABLE IF NOT EXISTS `mydb`.`match` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `match_category` VARCHAR(45) NOT NULL,
  `match_title` VARCHAR(100) NOT NULL,
  `match_content` TEXT NOT NULL,
  `match_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`posts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `isAnonymity` TINYINT(1) NULL DEFAULT 0,
  `posts_title` VARCHAR(45) NOT NULL,
  `posts_content` TEXT NOT NULL,
  `posts_tags` VARCHAR(45) NULL,
  `posts_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`, `student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `noti_date` TIMESTAMP NOT NULL,
  `noti_summarized` VARCHAR(45) NOT NULL COMMENT '通知概要',
  `noti_title` VARCHAR(45) NOT NULL,
  `noti_content` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`posts_comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`posts_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `comments_content` VARCHAR(45) NOT NULL,
  `comments_time` TIMESTAMP NOT NULL,
  `sub_comment_id` INT NOT NULL COMMENT '子评论的id',
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `posts_id`, `student_id`, `sub_comment_id`),
  INDEX `fk_posts_comments_posts1_idx` (`posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`video_series` ;

CREATE TABLE IF NOT EXISTS `mydb`.`video_series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_lecturer` VARCHAR(45) NOT NULL COMMENT '讲师',
  `course_title` VARCHAR(45) NOT NULL,
  `course_type` VARCHAR(45) NOT NULL,
  `watching_num` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video_collections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`video_collections` ;

CREATE TABLE IF NOT EXISTS `mydb`.`video_collections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `collection_time` TIMESTAMP NOT NULL,
  `video_series_id` INT NOT NULL,
  PRIMARY KEY (`id`, `video_series_id`, `student_id`),
  INDEX `fk_video_collections_video_series1_idx` (`video_series_id` ASC) VISIBLE,
  CONSTRAINT `fk_video_collections_video_series1`
    FOREIGN KEY (`video_series_id`)
    REFERENCES `mydb`.`video_series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`video` ;

CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `video_path` VARCHAR(255) NOT NULL,
  `video_title` VARCHAR(45) NOT NULL,
  `video_series_id` INT NOT NULL,
  PRIMARY KEY (`id`, `video_series_id`),
  INDEX `fk_video_video_series1_idx` (`video_series_id` ASC) VISIBLE,
  CONSTRAINT `fk_video_video_series1`
    FOREIGN KEY (`video_series_id`)
    REFERENCES `mydb`.`video_series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`elective_collections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`elective_collections` ;

CREATE TABLE IF NOT EXISTS `mydb`.`elective_collections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `collection_time` TIMESTAMP NOT NULL,
  `collecter_id` INT NOT NULL,
  `elective_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`, `elective_id`, `student_id`),
  INDEX `fk_elective_collections_elective_items1_idx` (`elective_id` ASC) VISIBLE,
  CONSTRAINT `fk_elective_collections_elective_items1`
    FOREIGN KEY (`elective_id`)
    REFERENCES `mydb`.`elective` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stu_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stu_notification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stu_notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `read_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '阅读状态 1已读 0未读',
  `notification_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `is_collect` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `notification_id`, `student_id`),
  INDEX `fk_stu_notification_notification1_idx` (`notification_id` ASC) VISIBLE,
  INDEX `fk_stu_notification_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_stu_notification_notification1`
    FOREIGN KEY (`notification_id`)
    REFERENCES `mydb`.`notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_notification_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`info_functions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`info_functions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`info_functions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `function_name` VARCHAR(45) NOT NULL,
  `img_path` VARCHAR(255) NOT NULL,
  `function_link` VARCHAR(255) NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`, `student_id`),
  INDEX `fk_info_functions_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_info_functions_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule_background`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`schedule_background` ;

CREATE TABLE IF NOT EXISTS `mydb`.`schedule_background` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `img_path` VARCHAR(255) NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`, `student_id`),
  INDEX `fk_schedule_background_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_background_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course_files` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `files_title` VARCHAR(45) NOT NULL,
  `files_path` VARCHAR(255) NOT NULL,
  `uploader_id` INT NOT NULL,
  `upload_time` TIMESTAMP NOT NULL,
  `course_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `uploader_id`, `course_id1`),
  INDEX `fk_course_files_course1_idx` (`course_id1` ASC) VISIBLE,
  CONSTRAINT `fk_course_files_course1`
    FOREIGN KEY (`course_id1`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`download_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`download_files` ;

CREATE TABLE IF NOT EXISTS `mydb`.`download_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `download_time` TIMESTAMP NOT NULL,
  `student_id` INT NOT NULL,
  `course_files_id` INT NOT NULL,
  PRIMARY KEY (`id`, `student_id`, `course_files_id`),
  INDEX `fk_download_files_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_download_files_course_files1_idx` (`course_files_id` ASC) VISIBLE,
  CONSTRAINT `fk_download_files_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_download_files_course_files1`
    FOREIGN KEY (`course_files_id`)
    REFERENCES `mydb`.`course_files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teacher_course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teacher_course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  INDEX `fk_teacher_course_course1_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_teacher_course_teacher1_idx` (`teacher_id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `course_id`, `teacher_id`),
  CONSTRAINT `fk_teacher_course_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_course_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stu_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stu_course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stu_course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`, `student_id`, `course_id`),
  INDEX `fk_stu_schedule_course_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_stu_schedule_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_stu_schedule_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_schedule_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`memo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`memo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`memo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `memo_content` VARCHAR(100) NOT NULL,
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`, `student_id`, `course_id`),
  INDEX `fk_memo_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_memo_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_memo_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_memo_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`register`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`register` ;

CREATE TABLE IF NOT EXISTS `mydb`.`register` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `register_status` ENUM("late", "truant", "arrive", "dayoff") NOT NULL,
  `register_time` TIMESTAMP NOT NULL,
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`, `student_id`, `course_id`),
  INDEX `fk_register_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_register_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_register_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_register_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts_collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`posts_collection` ;

CREATE TABLE IF NOT EXISTS `mydb`.`posts_collection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posts_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`, `posts_id`, `student_id`),
  INDEX `fk_posts_collection_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_posts_collection_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_collection_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_collection_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recently_read`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recently_read` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recently_read` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posts_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`, `posts_id`, `student_id`),
  INDEX `fk_recently_read_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_recently_read_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_recently_read_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recently_read_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`live_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`live_video` ;

CREATE TABLE IF NOT EXISTS `mydb`.`live_video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organiger_id` INT NOT NULL COMMENT '发起者id',
  `watching_num` INT NOT NULL,
  `live_title` VARCHAR(45) NOT NULL,
  `live_path` VARCHAR(255) NOT NULL COMMENT '直播网址',
  `start_time` TIMESTAMP NOT NULL,
  `live_status` TINYINT(1) NOT NULL COMMENT '直播状态 0已结束  1直播中',
  PRIMARY KEY (`id`, `organiger_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`video_record` ;

CREATE TABLE IF NOT EXISTS `mydb`.`video_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `video_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `watch_progress` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `video_id`, `student_id`),
  INDEX `fk_video_record_video1_idx` (`video_id` ASC) VISIBLE,
  INDEX `fk_video_record_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_video_record_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `mydb`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_record_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clock_in`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clock_in` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clock_in` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `clocked_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`, `student_id`),
  INDEX `fk_clock_in_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_clock_in_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teaching_evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teaching_evaluation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teaching_evaluation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `satisfaction` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `student_id`, `course_id`),
  INDEX `fk_teaching_evaluation_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_teaching_evaluation_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_teaching_evaluation_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teaching_evaluation_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
